# Generated by Django 6.0.2 on 2026-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='external_recipients',
            field=models.JSONField(blank=True, default=list, help_text='Список email-адресов внешних получателей', verbose_name='Внешние получатели'),
        ),
    ]
