# Generated by Django 6.0.2 on 2026-03-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_email', '0002_emailmessage_external_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Workspace'), ('microsoft', 'Microsoft 365')], max_length=20, verbose_name='Провайдер')),
                ('encrypted_access_token', models.BinaryField(verbose_name='Access Token (encrypted)')),
                ('encrypted_refresh_token', models.BinaryField(verbose_name='Refresh Token (encrypted)')),
                ('token_expires_at', models.DateTimeField(verbose_name='Срок действия Access Token')),
                ('scope', models.CharField(blank=True, max_length=500, verbose_name='Granted Scopes')),
                ('user_email', models.EmailField(help_text='Email-адрес пользователя на стороне Google/Microsoft', max_length=254, verbose_name='Email провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'OAuth-токен почты',
                'verbose_name_plural': 'OAuth-токены почты',
            },
        ),
    ]
