# Generated by Django 6.0.2 on 2026-02-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainView', '0005_contactrequest_replied_at_contactrequest_replied_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='handled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
