# Generated by Django 6.0.2 on 2026-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainView', '0006_alter_contactrequest_handled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=320, unique=True),
        ),
    ]
