"""initial

Revision ID: e0c787a032ce
Revises: 
Create Date: 2026-04-23 19:10:58.332490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c787a032ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS cms")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=150), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=150), server_default='', nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('handled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_by_id', sa.Integer(), nullable=True),
    sa.Column('reply_message', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_index(op.f('ix_cms_contact_requests_created_at'), 'contact_requests', ['created_at'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_contact_requests_handled'), 'contact_requests', ['handled'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_contact_requests_replied_at'), 'contact_requests', ['replied_at'], unique=False, schema='cms')
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), server_default='', nullable=False),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_index(op.f('ix_cms_news_category'), 'news', ['category'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_news_created_at'), 'news', ['created_at'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_news_published'), 'news', ['published'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_news_published_at'), 'news', ['published_at'], unique=False, schema='cms')
    op.create_index(op.f('ix_cms_news_slug'), 'news', ['slug'], unique=True, schema='cms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_news_slug'), table_name='news', schema='cms')
    op.drop_index(op.f('ix_cms_news_published_at'), table_name='news', schema='cms')
    op.drop_index(op.f('ix_cms_news_published'), table_name='news', schema='cms')
    op.drop_index(op.f('ix_cms_news_created_at'), table_name='news', schema='cms')
    op.drop_index(op.f('ix_cms_news_category'), table_name='news', schema='cms')
    op.drop_table('news', schema='cms')
    op.drop_index(op.f('ix_cms_contact_requests_replied_at'), table_name='contact_requests', schema='cms')
    op.drop_index(op.f('ix_cms_contact_requests_handled'), table_name='contact_requests', schema='cms')
    op.drop_index(op.f('ix_cms_contact_requests_created_at'), table_name='contact_requests', schema='cms')
    op.drop_table('contact_requests', schema='cms')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
