# Generated by Django 6.0.2 on 2026-02-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_create_hr_manager_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('status_change', 'Смена статуса')], db_index=True, max_length=20, verbose_name='Действие')),
                ('target_type', models.CharField(choices=[('employee', 'Сотрудник'), ('department', 'Отдел'), ('position', 'Должность'), ('vacancy', 'Вакансия'), ('application', 'Отклик'), ('time_tracking', 'Учёт времени'), ('document', 'Документ')], db_index=True, max_length=30, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('target_repr', models.CharField(blank=True, max_length=500, verbose_name='Описание объекта')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий HR',
                'verbose_name_plural': 'Журнал действий HR',
                'ordering': ['-created_at'],
            },
        ),
    ]
