# Generated by Django 6.0.2 on 2026-02-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hractionlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='hr.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='hractionlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='hr.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='hractionlog',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='hr.position', verbose_name='Должность'),
        ),
    ]
