# Generated by Django 6.0.2 on 2026-02-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hractionlog_department_hractionlog_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hractionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Журнал действий', 'verbose_name_plural': 'Журнал действий'},
        ),
        migrations.AddField(
            model_name='hractionlog',
            name='module',
            field=models.CharField(choices=[('hr', 'HR'), ('news', 'Новости'), ('profile', 'Профиль'), ('contacts', 'Обращения'), ('auth', 'Авторизация'), ('admin', 'Администрирование'), ('other', 'Другое')], db_index=True, default='other', max_length=30, verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='hractionlog',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='hractionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('status_change', 'Смена статуса'), ('login', 'Вход'), ('logout', 'Выход'), ('view', 'Просмотр'), ('upload', 'Загрузка'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='hractionlog',
            name='target_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('department', 'Отдел'), ('position', 'Должность'), ('vacancy', 'Вакансия'), ('application', 'Отклик'), ('time_tracking', 'Учёт времени'), ('document', 'Документ'), ('news', 'Новость'), ('profile', 'Профиль'), ('contact_request', 'Обращение'), ('user', 'Пользователь'), ('auth', 'Авторизация'), ('other', 'Другое')], db_index=True, max_length=30, verbose_name='Тип объекта'),
        ),
    ]
