# Generated by Django 6.0.2 on 2026-02-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hired', 'Приём на работу'), ('dismissed', 'Увольнение'), ('transfer', 'Перемещение'), ('promotion', 'Повышение'), ('demotion', 'Понижение'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Тип события')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер приказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personnel_history', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_history', to='hr.employee', verbose_name='Сотрудник')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='hr.department', verbose_name='Из отдела')),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='hr.position', verbose_name='Из должности')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='hr.department', verbose_name='В отдел')),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='hr.position', verbose_name='В должность')),
            ],
            options={
                'verbose_name': 'Кадровая история',
                'verbose_name_plural': 'Кадровая история',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
