# Generated by Django 6.0.2 on 2026-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_create_hr_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Банковский счёт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Премия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_data',
            field=models.TextField(blank=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='employee',
            name='safety_cert_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия сертификата ОТ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='safety_cert_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата ОТ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sro_permit_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия допуска СРО'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sro_permit_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер допуска СРО'),
        ),
    ]
