# Generated by Django 6.0.2 on 2026-02-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_document_application_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('initial_password', models.CharField(help_text='Пароль, сгенерированный при создании аккаунта. Сотрудник должен сменить его при первом входе.', max_length=128, verbose_name='Начальный пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Аккаунт сотрудника',
                'verbose_name_plural': 'Аккаунты сотрудников',
                'ordering': ['-created_at'],
            },
        ),
    ]
