# Generated by Django 6.0.2 on 2026-02-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_migrate_phone_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
