# Generated by Django 6.0.2 on 2026-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_remove_employee_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['index', 'name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['index', 'title'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='department',
            name='index',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='position',
            name='index',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Индекс'),
        ),
    ]
