# Generated by Django 6.0.2 on 2026-03-20 12:34

import django.db.models.deletion
import hr.department_files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_populate_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='hr.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Папка отдела',
                'verbose_name_plural': 'Папки отделов',
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to=hr.department_files._department_file_path, verbose_name='Файл')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_department_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hr.departmentfolder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл отдела',
                'verbose_name_plural': 'Файлы отделов',
                'ordering': ['-created_at'],
            },
        ),
    ]
