# Generated by Django 6.0.2 on 2026-03-05 12:32

import django.db.models.deletion
import messenger.infrastructure.ltree_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('direct', 'Личный'), ('group', 'Групповой'), ('secret', 'Секретный (E2EE)')], db_index=True, default='direct', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(blank=True, default='', help_text='For group chats. Direct/secret chats derive title from members.', max_length=300, verbose_name='Название')),
                ('current_pts', models.BigIntegerField(default=0, help_text='Global sequence number for this room.', verbose_name='Текущий PTS')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Аватар комнаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комната чата',
                'verbose_name_plural': 'Комнаты чатов',
                'db_table': 'messenger_chat_room',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatUserReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='Matches auth.User.pk — no FK constraint.', unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL аватара')),
                ('department_path', messenger.infrastructure.ltree_fields.LTreeField(blank=True, db_index=True, default='', max_length=1024, verbose_name='Путь отдела')),
                ('department_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название отдела')),
                ('position_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность')),
                ('is_online', models.BooleanField(db_index=True, default=False, verbose_name='Онлайн')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз онлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реплика пользователя (чат)',
                'verbose_name_plural': 'Реплики пользователей (чат)',
                'db_table': 'messenger_chat_user_replica',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('admin', 'Администратор'), ('owner', 'Владелец')], default='member', max_length=20, verbose_name='Роль')),
                ('local_pts', models.BigIntegerField(default=0, help_text='Last pts this user has acknowledged.', verbose_name='Локальный PTS')),
                ('unread_count', models.IntegerField(default=0, verbose_name='Непрочитанные')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Без звука')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее чтение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messenger.chatroom', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messenger.chatuserreplica', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в чате',
                'verbose_name_plural': 'Участия в чатах',
                'db_table': 'messenger_chat_membership',
                'ordering': ['-is_pinned', '-last_read_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='rooms', through='messenger.ChatMembership', to='messenger.chatuserreplica', verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='AuthKeyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_pub_key', models.BinaryField(help_text='32-byte X25519 public key for ECDH key exchange.', max_length=32, verbose_name='Публичный ключ X25519')),
                ('signed_prekey', models.BinaryField(help_text='Signed pre-key for async E2EE initiation.', max_length=32, verbose_name='Подписанный pre-key')),
                ('prekey_signature', models.BinaryField(help_text='Ed25519 signature over signed_prekey.', max_length=64, verbose_name='Подпись pre-key')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_key_bundle', to='messenger.chatuserreplica', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка ключей',
                'verbose_name_plural': 'Связки ключей',
                'db_table': 'messenger_auth_key_bundle',
            },
        ),
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_blob', models.BinaryField(help_text='AES-256-GCM ciphertext (secret) or plaintext JSON (direct/group).', verbose_name='Зашифрованные данные')),
                ('msg_key', models.BinaryField(blank=True, default=b'', help_text='128-bit msg_key for E2EE verification. Empty for non-secret rooms.', max_length=16, verbose_name='Ключ сообщения')),
                ('msg_type', models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('system', 'Системное'), ('key_exchange', 'Обмен ключами')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('pts', models.BigIntegerField(db_index=True, help_text='Room-level monotonic sequence number.', verbose_name='PTS')),
                ('pts_count', models.IntegerField(default=1, help_text='How many pts slots this update occupies.', verbose_name='PTS count')),
                ('seq_no', models.BigIntegerField(blank=True, help_text='Strictly increasing per-sender counter. Verified client-side.', null=True, verbose_name='Seq No (encrypted)')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messenger.encryptedmessage', verbose_name='Ответ на')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chatroom', verbose_name='Комната')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='messenger.chatuserreplica', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messenger_encrypted_message',
                'ordering': ['pts'],
                'indexes': [models.Index(fields=['room', 'pts'], name='msg_room_pts_idx'), models.Index(fields=['room', 'created_at'], name='msg_room_created_idx')],
            },
        ),
    ]
