# Generated by Django 6.0.2 on 2026-03-10 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chatroom_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='messenger.chatuserreplica', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение чата',
                'verbose_name_plural': 'Вложения чатов',
                'db_table': 'messenger_chat_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
