# Generated by Django 6.0.2 on 2026-03-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_populate_indexes'),
        ('tasks', '0003_notification_tasklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('working', 'Рабочий'), ('weekend', 'Выходной'), ('holiday', 'Праздник'), ('short', 'Сокращённый')], default='working', max_length=20, verbose_name='Тип дня')),
                ('working_days_since_epoch', models.IntegerField(db_index=True, default=0, help_text='Используется для математического расчета разницы в рабочих днях за O(1)', verbose_name='Рабочих дней с начала эпохи')),
            ],
            options={
                'verbose_name': 'Производственный день',
                'verbose_name_plural': 'Производственный календарь',
                'db_table': 'hr_production_day',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_working_days',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано, дедлайн будет рассчитан автоматически с учетом календаря.', null=True, verbose_name='Оценка (раб. дни)'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('common', 'Общее'), ('department', 'Отдел'), ('personal', 'Личное')], default='common', max_length=20, verbose_name='Тип события')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('rrule', models.CharField(blank=True, help_text='Например: FREQ=WEEKLY;BYDAY=MO,WE,FR', max_length=255, verbose_name='Правило повторения (RRULE)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='hr.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'db_table': 'hr_calendar_event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='Исходная дата вхождения')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('new_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Новое начало')),
                ('new_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Новый конец')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='tasks.calendarevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Исключение события',
                'verbose_name_plural': 'Исключения событий',
                'db_table': 'hr_event_exception',
                'unique_together': {('event', 'original_date')},
            },
        ),
    ]
