# Generated by Django 6.0.2 on 2026-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_productionday_task_estimated_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='conference_room_id',
            field=models.CharField(blank=True, default='', help_text='Автоматически заполняется при создании события с типом «Конференция»', max_length=50, verbose_name='ID комнаты ВКС'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('common', 'Общее'), ('department', 'Отдел'), ('personal', 'Личное'), ('conference', 'Конференция')], default='common', max_length=20, verbose_name='Тип события'),
        ),
    ]
