"""initial

Revision ID: 2096193f39e5
Revises: 
Create Date: 2026-04-23 19:11:46.058979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2096193f39e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS email")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_created_at'), 'oauth_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('folder', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('snippet', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('to_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bcc_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dlp_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['oauth_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_created_at'), 'email_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_user_id'), 'email_messages', ['user_id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_metadata_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_created_at'), 'email_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_attachments_message_id'), 'email_attachments', ['message_id'], unique=False)
    op.create_table('recipient_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipient_statuses_created_at'), 'recipient_statuses', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipient_statuses_message_id'), 'recipient_statuses', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipient_statuses_message_id'), table_name='recipient_statuses')
    op.drop_index(op.f('ix_recipient_statuses_created_at'), table_name='recipient_statuses')
    op.drop_table('recipient_statuses')
    op.drop_index(op.f('ix_email_attachments_message_id'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_created_at'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_email_messages_user_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_created_at'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_created_at'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    # ### end Alembic commands ###
