"""
Django settings for HTQWeb project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import socket
import ipaddress

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем ТОЛЬКО Gmail-настройки из .env (Updated to fix redirect_uri)
_env_file = BASE_DIR.parent / '.env'
if _env_file.is_file():
    with open(_env_file, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, value = line.partition('=')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key.startswith(('GMAIL_', 'OAUTH_', 'GOOGLE_OAUTH_', 'MICROSOFT_OAUTH_')):
                os.environ[key] = value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-y(sdket)xf9b)@9czfd3wh5yi$192r39-gb(h+_=+ififtje#a'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

# CORS / CSRF configuration
# By default in development we allow all origins. In production, set
# the environment variables below to restrict origins safely.
#
# - CORS_ALLOW_ALL_ORIGINS: 'True' or 'False'
# - CORS_ALLOWED_ORIGINS: comma-separated list like 'https://example.com,https://app.example.com'
# - CSRF_TRUSTED_ORIGINS: comma-separated list with scheme, e.g. 'https://example.com'

CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'

# If not allowing all origins, read explicit allowed origins from env var
if not CORS_ALLOW_ALL_ORIGINS:
    raw = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    CORS_ALLOWED_ORIGINS = [o.strip() for o in raw.split(',') if o.strip()]

# Allow credentials (cookies/auth headers) over CORS when needed
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'True') == 'True'

# CSRF trusted origins (Django requires scheme + host, e.g. 'https://example.com')
raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in raw_csrf.split(',') if o.strip()]

# In DEBUG mode, add common local development origins
if DEBUG:
    local_origins = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://192.168.2.106:3000',
        'http://192.168.2.54:3000',
    ]
    # Auto-detect local IPs for frontend dev servers (optional, DEBUG only)
    def _get_local_ips():
        ips = set()
        try:
            hostname = socket.gethostname()
            for info in socket.getaddrinfo(hostname, None):
                ip = info[4][0]
                if ':' in ip:
                    continue  # skip IPv6
                try:
                    ip_obj = ipaddress.ip_address(ip)
                    if not ip_obj.is_loopback:
                        ips.add(ip)
                except ValueError:
                    continue
        except Exception:
            pass
        return ips

    raw_ports = os.environ.get('FRONTEND_PORTS', '3000,5173')
    ports = [p.strip() for p in raw_ports.split(',') if p.strip()]
    for ip in _get_local_ips():
        for port in ports:
            local_origins.append(f'http://{ip}:{port}')

    CSRF_TRUSTED_ORIGINS.extend(local_origins)
    
    # When CORS_ALLOW_CREDENTIALS is True, we MUST specify origins
    if CORS_ALLOW_CREDENTIALS:
        CORS_ALLOW_ALL_ORIGINS = False
        CORS_ALLOWED_ORIGINS = list(set(local_origins))

INSTALLED_APPS = [
    'daphne',                    # ASGI server — must be first to override runserver
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainView',
    'media_manager',
    'hr',
    'tasks',
    'messenger',                 # E2EE corporate messenger (isolated module)
    'internal_email',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',   # compress all text/JSON responses
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'hr.middleware.AuditLogMiddleware',
]

ROOT_URLCONF = 'HTQWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HTQWeb.wsgi.application'
ASGI_APPLICATION = 'HTQWeb.asgi.application'

# --- Django Channels (WebSocket layer) ---
CHANNEL_LAYERS = {
    'default': {
        # In production: use Redis channel layer (see docker-compose.yml)
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {'hosts': [('redis', 6379)]},
        # In development: in-memory layer (single-process only)
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
        'CONN_MAX_AGE': 600,  # держим соединения живыми 10 мин
    }
}


# Cache — Redis (если доступен), иначе in-memory LocMemCache
CACHES = {
    'default': {
        'BACKEND': os.environ.get(
            'CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.environ.get('CACHE_LOCATION', 'unique-snowflake'),
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic output for production
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Conference / SFU signaling source of truth (backend-driven).
# Frontend should never hardcode SFU host.
# If CONFERENCE_SFU_URL is empty, frontend builds ws/wss URL using current origin + CONFERENCE_SFU_PATH.
CONFERENCE_SFU_URL = (
    os.environ.get('CONFERENCE_SFU_URL')
    or os.environ.get('SFU_SIGNALING_URL')
    or os.environ.get('VITE_SFU_URL')
    or ''
)
CONFERENCE_SFU_PATH = os.environ.get('CONFERENCE_SFU_PATH', '/ws/sfu/')
# Optional JSON array for frontend RTCConfiguration. Example:
# [
#   {"urls":["stun:stun.l.google.com:19302"]},
#   {"urls":["turn:global.turn.twilio.com:3478?transport=udp","turns:global.turn.twilio.com:443?transport=tcp"],"username":"twilio-user","credential":"twilio-pass"},
#   {"urls":["turn:your-project.metered.live:80?transport=udp","turn:your-project.metered.live:443?transport=tcp"],"username":"metered-user","credential":"metered-pass"}
# ]
CONFERENCE_ICE_SERVERS = os.environ.get('CONFERENCE_ICE_SERVERS', '')

# ═══════════════════════════════════════════════════════════════════════════
#  File Storage — S3 / MinIO (opt-in via environment variables)
# ═══════════════════════════════════════════════════════════════════════════
_STORAGE_BACKEND = os.environ.get('STORAGE_BACKEND', 'local')  # 'local' | 's3'

if _STORAGE_BACKEND == 's3':
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.environ.get("AWS_ACCESS_KEY_ID", ""),
                "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", ""),
                "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME", "htqweb-media"),
                "endpoint_url": os.environ.get("AWS_S3_ENDPOINT_URL", ""),
                "region_name": os.environ.get("AWS_S3_REGION_NAME", "us-east-1"),
                "default_acl": None,
                "querystring_auth": True,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    _s3_custom_domain = os.environ.get("AWS_S3_CUSTOM_DOMAIN", "")
    if _s3_custom_domain:
        STORAGES["default"]["OPTIONS"]["custom_domain"] = _s3_custom_domain
        MEDIA_URL = f'https://{_s3_custom_domain}/'

REST_FRAMEWORK = {
    # Используем JWT для авторизации
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # По умолчанию доступ только авторизованным
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Пагинация — разумные лимиты для 7-9 пользователей
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Throttling — защита от перегрузки и abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',   # незалогиненные: 30 запросов/мин
        'user': '120/minute',  # залогиненные: 120 запросов/мин
    },
}

# ---------- JWT ----------
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'hr.roles': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'hr.permissions': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'internal_email': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Email Backend Settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@hi-tech-group.com'

# List of emails that will receive notifications about new contact requests
STAFF_NOTIFICATION_EMAILS = ['admin@example.com'] # Replace with real staff emails

# Gmail SMTP Settings (LEGACY — kept for fallback, will be removed)
GMAIL_ADDRESS = os.environ.get('GMAIL_ADDRESS', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

# ═══════════════════════════════════════════════════════════════════════════
#  OAuth 2.0 — per-user email sending (Google Workspace / Microsoft 365)
# ═══════════════════════════════════════════════════════════════════════════

# AES-256-GCM encryption key for OAuth tokens (base64-encoded 32-byte key)
# Generate: python -c "import os,base64; print(base64.b64encode(os.urandom(32)).decode())"
OAUTH_ENCRYPTION_KEY = os.environ.get('OAUTH_ENCRYPTION_KEY', '')

# Google OAuth 2.0 (Gmail API)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    'GOOGLE_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/email/oauth/callback/'
)

# Microsoft OAuth 2.0 (Graph API)
MICROSOFT_OAUTH_CLIENT_ID = os.environ.get('MICROSOFT_OAUTH_CLIENT_ID', '')
MICROSOFT_OAUTH_CLIENT_SECRET = os.environ.get('MICROSOFT_OAUTH_CLIENT_SECRET', '')
MICROSOFT_OAUTH_REDIRECT_URI = os.environ.get(
    'MICROSOFT_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/email/oauth/callback/'
)
MICROSOFT_OAUTH_TENANT_ID = os.environ.get('MICROSOFT_OAUTH_TENANT_ID', 'common')

# Session engine (needed for OAuth state CSRF protection)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
