"""initial

Revision ID: 644483c8e978
Revises: 
Create Date: 2026-04-23 19:11:43.253117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644483c8e978'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS media")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path'),
    schema='media'
    )
    op.create_index(op.f('ix_media_file_metadata_created_at'), 'file_metadata', ['created_at'], unique=False, schema='media')
    op.create_index(op.f('ix_media_file_metadata_owner_id'), 'file_metadata', ['owner_id'], unique=False, schema='media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_file_metadata_owner_id'), table_name='file_metadata', schema='media')
    op.drop_index(op.f('ix_media_file_metadata_created_at'), table_name='file_metadata', schema='media')
    op.drop_table('file_metadata', schema='media')
    # ### end Alembic commands ###
